package Application1;

import static Application1.Responsable.loginad;
import static Application1.etudiant.loginet;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import net.proteanit.sql.DbUtils;
import java.sql.PreparedStatement;
import java.text.MessageFormat;
import java.util.Locale;
import javax.print.PrintException;
import javax.swing.JTable;

/**
 *
 * @author QUEEN-HP
 */
public class gererabsence extends javax.swing.JFrame {

    /**
     * Creates new form gererabsence
     */
     Connexion conn =new Connexion();
        private void Affichetableabs() {
        Statement st;
        ResultSet rs;
        try{
            String sql="select absence.numseance'Numéro séance',etudiant.login'login',etudiant.nom'Nom',etudiant.prenom'Prenom',enseignant.nom'Enseignant',absence.date'Date Absences' from absence,etudiant,classe,enseignant where classe.niveau='"+niv.getText()+"'"
                    + "and classe.libelle='"+lib.getText()+"'and classe.filière='"+fil.getText()+"'and classe.id_classe=etudiant.id_classe and absence.id_etudiant=etudiant.id_etudiant and absence.id_enseignant=enseignant.id_enseignant ";        
            st=conn.getconnexion().createStatement();
            rs=st.executeQuery(sql);
            Tableabs.setModel(DbUtils.resultSetToTableModel(rs));

            }catch(Exception ex){
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }

        }
    
    
     public void date(){
        
        Calendar cal=new GregorianCalendar();
        int jo=cal.get(Calendar.DAY_OF_MONTH);
        int mois=cal.get(Calendar.MONTH);
        int annee=cal.get(Calendar.YEAR);
        
        int min=cal.get(Calendar.MINUTE);
        int sec=cal.get(Calendar.SECOND);
        int he=cal.get(Calendar.HOUR_OF_DAY);
        
        heure.setText("DATE :  "+he+" :"+min+" :"+sec);
        date.setText(jo+"-"+(mois+1)+"-"+annee);
        
    }
    
     void Fermer(){
        dispose();
    }
    
    
    public gererabsence() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Gerer Absences");
        date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        loginadg = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        heure = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        niv = new javax.swing.JLabel();
        lib = new javax.swing.JLabel();
        fil = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        retour = new javax.swing.JButton();
        graphe = new javax.swing.JButton();
        consulter1 = new javax.swing.JButton();
        annuler1 = new javax.swing.JButton();
        email1 = new javax.swing.JButton();
        imprimer1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tableabs = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 102));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\QUEEN-HP\\Desktop\\icone\\Admin-icon.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 140, 140);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Zone Amdministration ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 10, 430, 60);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(70, 200, 650, 10);

        loginadg.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        loginadg.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(loginadg);
        loginadg.setBounds(510, 150, 290, 40);

        date.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        date.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(date);
        date.setBounds(660, 100, 140, 40);

        heure.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        heure.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(heure);
        heure.setBounds(520, 100, 150, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gerer Les Absences");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(250, 60, 150, 20);

        niv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(niv);
        niv.setBounds(170, 160, 40, 30);

        lib.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(lib);
        lib.setBounds(220, 160, 70, 30);

        fil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(fil);
        fil.setBounds(310, 160, 110, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Classe :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 160, 70, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        retour.setBackground(new java.awt.Color(51, 255, 51));
        retour.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        retour.setForeground(new java.awt.Color(255, 255, 0));
        retour.setText("RETOUR");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        jPanel2.add(retour);
        retour.setBounds(10, 330, 110, 40);

        graphe.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        graphe.setText("Graphe");
        graphe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grapheActionPerformed(evt);
            }
        });
        jPanel2.add(graphe);
        graphe.setBounds(510, 270, 100, 40);

        consulter1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        consulter1.setText("Consulter");
        consulter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulter1ActionPerformed(evt);
            }
        });
        jPanel2.add(consulter1);
        consulter1.setBounds(150, 270, 100, 40);

        annuler1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        annuler1.setText("Annuler");
        annuler1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annuler1ActionPerformed(evt);
            }
        });
        jPanel2.add(annuler1);
        annuler1.setBounds(270, 270, 100, 40);

        email1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        email1.setText("Email");
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        jPanel2.add(email1);
        email1.setBounds(640, 270, 100, 40);

        imprimer1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        imprimer1.setText("Imprimer");
        imprimer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimer1ActionPerformed(evt);
            }
        });
        jPanel2.add(imprimer1);
        imprimer1.setBounds(390, 270, 100, 40);

        Tableabs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numéro séance", "login", "Nom", "Prenom", "Enseignant", "Date Absences"
            }
        ));
        jScrollPane1.setViewportView(Tableabs);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(130, 30, 640, 180);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 819, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {                                       
        Responsable res=new Responsable();
        res.setVisible(true);
        res.loginad.setText(loginadg.getText());
        Fermer();
    }                                      

    private void consulter1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        Affichetableabs();
    }                                          

    private void annuler1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       int ligne=Tableabs.getSelectedRow();
       String cel=Tableabs.getModel().getValueAt(ligne, 0).toString();
       String sql="delete from absence where numseance='"+cel+"'";
       
       Statement st;
       
       try{
           
           st=conn.getconnexion().createStatement();
           st.executeUpdate(sql);
            JOptionPane.showConfirmDialog(null,"Vous-été sure de Anuler ","Annuler le ligne",JOptionPane.YES_NO_CANCEL_OPTION);
            Affichetableabs();
           
       }catch(Exception ex){
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
           JOptionPane.showMessageDialog(null,"ERREUR");
       }
       
    }                                        

    private void imprimer1ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        MessageFormat tete=new MessageFormat("Liste des Absences");
        MessageFormat pied=new MessageFormat("page[0,number,Integer]");
       
        try{
            Tableabs.print(JTable.PrintMode.FIT_WIDTH, tete, pied);
            
        }catch(Exception ex){
           Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }                                         

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
        emailabs em=new emailabs();
        em.setVisible(true);
        int ligne=Tableabs.getSelectedRow();
        String cel=Tableabs.getModel().getValueAt(ligne, 1).toString();
        em.email.setText(cel);
       
    }                                      

    private void grapheActionPerformed(java.awt.event.ActionEvent evt) {                                       
       grapheabs gr=new grapheabs();
        gr.setVisible(true);
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is ://not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gererabsence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gererabsence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gererabsence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gererabsence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gererabsence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JTable Tableabs;
    private javax.swing.JButton annuler1;
    private javax.swing.JButton consulter1;
    private javax.swing.JLabel date;
    private javax.swing.JButton email1;
    public static javax.swing.JLabel fil;
    private javax.swing.JButton graphe;
    private javax.swing.JLabel heure;
    private javax.swing.JButton imprimer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JLabel lib;
    public static javax.swing.JLabel loginadg;
    public static javax.swing.JLabel niv;
    private javax.swing.JButton retour;
    // End of variables declaration                   
}
