package Application1;

import java.awt.BorderLayout;
import java.awt.Color;
//import static java.awt.Color.RED;
import org.jfree.chart.ChartFactory;
//import org.jfree.chart.ChartFrame;
import org.jfree.chart.*;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author QUEEN-HP
 */
public class grapheabs extends javax.swing.JFrame {

    /**
     * Creates new form grapheabs
     */
    Connexion conn =new Connexion();
    public grapheabs() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        niveau = new javax.swing.JButton();
        panelbar = new javax.swing.JPanel();
        libelle = new javax.swing.JButton();
        filiere = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("cliquer Votre choix ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 0, 232, 40);

        niveau.setBackground(new java.awt.Color(0, 255, 255));
        niveau.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        niveau.setForeground(new java.awt.Color(153, 0, 153));
        niveau.setText("Par Niveau");
        niveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niveauActionPerformed(evt);
            }
        });
        jPanel1.add(niveau);
        niveau.setBounds(690, 60, 130, 40);

        panelbar.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelbar);
        panelbar.setBounds(10, 110, 880, 410);

        libelle.setBackground(new java.awt.Color(0, 255, 255));
        libelle.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        libelle.setForeground(new java.awt.Color(153, 0, 153));
        libelle.setText("Par Libelle");
        libelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleActionPerformed(evt);
            }
        });
        jPanel1.add(libelle);
        libelle.setBounds(60, 60, 130, 40);

        filiere.setBackground(new java.awt.Color(0, 255, 255));
        filiere.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        filiere.setForeground(new java.awt.Color(153, 0, 153));
        filiere.setText("Par Filière");
        filiere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filiereActionPerformed(evt);
            }
        });
        jPanel1.add(filiere);
        filiere.setBounds(400, 60, 130, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void niveauActionPerformed(java.awt.event.ActionEvent evt) {                                       
                    try{
                
            String sql="select count(absence.id_etudiant),classe.niveau from etudiant,absence,classe where classe.id_classe=etudiant.id_classe and"
            		+ " absence.id_etudiant=etudiant.id_etudiant";
                        JDBCCategoryDataset datset=new JDBCCategoryDataset(conn.getconnexion(), sql);
                /*datset.setValue(1,"taux", "1ere année");
                datset.setValue(2,"taux", "2eme année");
                datset.setValue(3,"taux", "3eme année");*/
                JFreeChart chart=ChartFactory.createBarChart("Diagramme des absences ","Niveau","taux d'absentéisme",datset,PlotOrientation.VERTICAL,false,true,true);
               // BarRenderer render=new BarRenderer();
                CategoryPlot plot=chart.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.RED);
                ChartPanel barpanel=new ChartPanel(chart);
                panelbar.removeAll();
                panelbar.add(barpanel, BorderLayout.CENTER);
                panelbar.validate();                
            }catch(Exception ex){
                ex.printStackTrace();
                
            }
    }                                      

    private void libelleActionPerformed(java.awt.event.ActionEvent evt) {                                        
                    try{
                
            String sql="select count(absence.id_etudiant),classe.libelle from etudiant,absence,classe where classe.id_classe=etudiant.id_classe "
            		+ "and absence.id_etudiant=etudiant.id_etudiant";
                JDBCCategoryDataset datset=new JDBCCategoryDataset(conn.getconnexion(), sql);
                JFreeChart chart=ChartFactory.createBarChart("Diagramme des absences ", "libelle", "taux d’absentéisme",datset,PlotOrientation.VERTICAL,false,true,true);
                        //creatlineChart("informatique","");
              //  BarRenderer render=new BarRenderer();
                CategoryPlot plot=chart.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.RED);
                ChartPanel barpanel=new ChartPanel(chart);
                panelbar.removeAll();
                panelbar.add(barpanel, BorderLayout.CENTER);
                panelbar.validate();
                
                
                
                
                /*chartFrame frame=new chartFrame("Query chart",chart);
                frame.setVisible(true);
                frame.size(200,400);    */
                
            }catch(Exception ex){
                ex.printStackTrace();
                
            }
    }                                       

    private void filiereActionPerformed(java.awt.event.ActionEvent evt) {                                        
                
            try{
                
            String sql="select count(absence.id_etudiant),classe.filière from etudiant,absence,classe where classe.id_classe=etudiant.id_classe and "
            		+ "absence.id_etudiant=etudiant.id_etudiant";
                JDBCCategoryDataset datset=new JDBCCategoryDataset(conn.getconnexion(), sql);
                JFreeChart chart=ChartFactory.createBarChart("Diagramme des absences ", "Filière", "taux d’absentéisme", datset,PlotOrientation.VERTICAL,false,true,false);
                        //creatlineChart("informatique","");
               // BarRenderer render=new BarRenderer();
                CategoryPlot plot=chart.getCategoryPlot();
                plot.setRangeGridlinePaint(Color.RED);
                ChartPanel barpanel=new ChartPanel(chart);
                panelbar.removeAll();
                panelbar.add(barpanel, BorderLayout.CENTER);
                panelbar.validate();
                
                
                
                
                /*chartFrame frame=new chartFrame("Query chart",chart);
                frame.setVisible(true);
                frame.size(200,400);    */
                
            }catch(Exception ex){
                ex.printStackTrace();
                
            }
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(grapheabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(grapheabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(grapheabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(grapheabs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new grapheabs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton filiere;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton libelle;
    private javax.swing.JButton niveau;
    private javax.swing.JPanel panelbar;
    // End of variables declaration                   
}