package Application1;

import java.awt.event.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.*;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


@SuppressWarnings("InitializerMayBeStatic")
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */ 
    void Fermer(){
        dispose();
    }
    Connexion conn = new Connexion();
    public login() {
        initComponents(); 
        this.setLocationRelativeTo(null);
        this.setTitle("Login");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        mp = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        statut = new javax.swing.JComboBox<>();
        connx = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\QUEEN-HP\\Desktop\\icone\\Users-icon.png")); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 10, 130, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Login :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(100, 150, 110, 29);

        login.setDisabledTextColor(new java.awt.Color(153, 153, 153));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(230, 150, 210, 29);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Mot de passe :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 240, 184, 29);
        jPanel1.add(mp);
        mp.setBounds(230, 240, 210, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("STATUT :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 360, 130, 29);

        statut.setBackground(new java.awt.Color(204, 255, 255));
        statut.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        statut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aucun", "Etudiant", "Enseignant", "Responsable administratif" }));
        statut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statutActionPerformed(evt);
            }
        });
        jPanel1.add(statut);
        statut.setBounds(230, 360, 210, 30);
        statut.getAccessibleContext().setAccessibleName("");

        connx.setBackground(new java.awt.Color(204, 255, 204));
        connx.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        connx.setForeground(new java.awt.Color(153, 153, 153));
        connx.setText("Connexion");
        connx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connxActionPerformed(evt);
            }
        });
        jPanel1.add(connx);
        connx.setBounds(140, 460, 190, 31);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(230, 180, 210, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void statutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void connxActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
         
      if(statut.getSelectedItem()=="Etudiant"){  
      String sql1="select * from etudiant where login='"+login.getText()+"'and pwd='"+mp.getText()+"'";
      Statement st;
          try {
              st = conn.getconnexion().createStatement();
              ResultSet rs=st.executeQuery(sql1);
              while(rs.next()){
                  etudiant et=new etudiant();
                  et.setVisible(true);  
                  et.loginet.setText(login.getText());
                  Fermer();

      }
      }   catch (SQLException ex) {
              Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
          }
          
      }
      if(statut.getSelectedItem()=="Enseignant"){
      String sql2="select * from enseignant where login='"+login.getText()+"'and pwd='"+mp.getText()+"'";
      Statement st;
          try {
              st = conn.getconnexion().createStatement();
              ResultSet rs=st.executeQuery(sql2);
              while(rs.next()){
                  presence pr=new presence();
                  pr.setVisible(true);
                  pr.llogin1.setText(login.getText());
                  Fermer();
              }
          } catch (SQLException ex) {
              Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
          }
          
      }
      if(statut.getSelectedItem()=="Responsable administratif"){
      String sql3="select * from responsable where login='"+login.getText()+"'and pwd='"+mp.getText()+"'";
      Statement st;
          try {
              st = conn.getconnexion().createStatement();
              ResultSet rs=st.executeQuery(sql3);
              while(rs.next()){
                   Responsable res=new Responsable();
                  res.setVisible(true);
                  res.loginad.setText(login.getText());
                  Fermer();
          }
                  
      }   catch (SQLException ex) {
              Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
          }
          
      
        
      } 
      
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws Exception {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>  
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new login().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
               
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JToggleButton connx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField login;
    public static javax.swing.JPasswordField mp;
    private javax.swing.JComboBox<String> statut;
    // End of variables declaration                   
}
