package Application1;

import static Application1.enseignantlistepresence.llogin;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author QUEEN-HP
 */
public class Responsable extends javax.swing.JFrame {

    /** Creates new form Responsable */
    
    public void date(){
        
        Calendar cal=new GregorianCalendar();
        int jo=cal.get(Calendar.DAY_OF_MONTH);
        int mois=cal.get(Calendar.MONTH);
        int annee=cal.get(Calendar.YEAR);
        
        int min=cal.get(Calendar.MINUTE);
        int sec=cal.get(Calendar.SECOND);
        int he=cal.get(Calendar.HOUR_OF_DAY);
        
        heure.setText("DATE :  "+he+" :"+min+" :"+sec);
        date.setText(jo+"-"+(mois+1)+"-"+annee);
        
    }
    
     void Fermer(){
        dispose();
    }
    
    public Responsable() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Responsable administratif");
        date();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        loginad = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        heure = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        retour = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fi = new javax.swing.JComboBox<>();
        ni = new javax.swing.JComboBox<>();
        li = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administation");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 102));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\QUEEN-HP\\Desktop\\icone\\Admin-icon.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 20, 140, 140);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Zone Amdministration ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(200, 10, 430, 60);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(60, 172, 650, 10);

        loginad.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        loginad.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(loginad);
        loginad.setBounds(480, 130, 290, 40);

        date.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        date.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(date);
        date.setBounds(630, 70, 140, 40);

        heure.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        heure.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.add(heure);
        heure.setBounds(490, 70, 150, 40);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        retour.setBackground(new java.awt.Color(51, 255, 51));
        retour.setFont(new java.awt.Font("Trebuchet MS", 3, 18)); // NOI18N
        retour.setForeground(new java.awt.Color(255, 255, 0));
        retour.setText("RETOUR");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });
        jPanel2.add(retour);
        retour.setBounds(0, 250, 110, 40);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 24, 70, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Filière :");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(210, 150, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setText("NIveau :");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(210, 50, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel7.setText("Libellé :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(210, 100, 60, 30);

        fi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "informatique", "mathematique", "physique", "biologie", "chimie", "droit", "economie", "gestion" }));
        jPanel2.add(fi);
        fi.setBounds(320, 150, 170, 30);

        ni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel2.add(ni);
        ni.setBounds(320, 50, 170, 30);

        li.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "licence", "master", "ingenierie", "doctorat" }));
        jPanel2.add(li);
        li.setBounds(320, 100, 170, 30);

        jButton1.setBackground(new java.awt.Color(102, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Gerer Absences ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(613, 253, 150, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {                                       
        login log=new login();
        log.setVisible(true);
        Fermer();
    }                                      

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        gererabsence ger=new gererabsence();
        ger.setVisible(true);
        ger.loginadg.setText(loginad.getText());
        ger.lib.setText((String) li.getSelectedItem());
        ger.fil.setText((String) fi.getSelectedItem());
        ger.niv.setText((String) ni.getSelectedItem());
        Fermer();        
    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Responsable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Responsable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel date;
    public static javax.swing.JComboBox<String> fi;
    private javax.swing.JLabel heure;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JComboBox<String> li;
    public static javax.swing.JLabel loginad;
    public static javax.swing.JComboBox<String> ni;
    private javax.swing.JButton retour;
    // End of variables declaration                   

}

